"use client";

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { format } from "date-fns";

const styles = StyleSheet.create({
    page: {
        padding: 60,
        fontFamily: "Helvetica",
    },
    title: {
        fontSize: 24,
        marginBottom: 20,
        fontWeight: "bold",
        color: "#4f46e5",
    },
    section: {
        marginBottom: 20,
    },
    text: {
        fontSize: 12,
        color: "#475569",
        lineHeight: 1.5,
    },
    bold: {
        fontWeight: "bold",
        color: "#1e293b",
    },
    footer: {
        marginTop: 50,
        fontSize: 10,
        color: "#94a3b8",
        textAlign: "center",
    },
});

export const LeaseNoticePDF = ({ tenantName, address, newRent, effectiveDate }: {
    tenantName: string;
    address: string;
    newRent: number;
    effectiveDate: string;
}) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <Text style={styles.title}>Lease Rent Increase Notice</Text>

            <View style={styles.section}>
                <Text style={styles.text}>Date: {format(new Date(), "MM/dd/yyyy")}</Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.text}>To: <Text style={styles.bold}>{tenantName}</Text></Text>
                <Text style={styles.text}>Address: {address}</Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.text}>
                    Pursuant to your lease agreement, we are writing to notify you that your base rent will increase effective <Text style={styles.bold}>{effectiveDate}</Text>.
                </Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.text}>New Monthly Rent: <Text style={styles.bold}>${newRent.toLocaleString("en-US", { minimumFractionDigits: 2 })}</Text></Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.text}>
                    Please update your payment records accordingly. If you have any questions, please contact the management office.
                </Text>
            </View>

            <Text style={styles.footer}>Generated by RentClock - Modern Lease Management</Text>
        </Page>
    </Document>
);
